version: '3.7'

services:
  proxy:
    image: nginx:alpine
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
    volumes:
      - app-staticfiles:/usr/share/nginx/html/public:ro
    networks:
      - internal
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=traefik_net
        - traefik.port=80
        - traefik.frontend.rule=Host:mete.chaosdorf.space
  app:
    image: chaosdorf/mete:latest
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=yoloyolo123
      - DATABASE_URL=postgresql://mete:mete@db:5432/mete?pool=5&timeout=5000
      - SENTRY_DSN=
    volumes:
      - app-staticfiles:/app/public
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: mete
      POSTGRES_PASSWORD: mete
      POSTGRES_DB: mete
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  app-staticfiles:
  db-data:

networks:
  internal:
    driver: overlay
  traefik:
    driver: overlay
    external: true
    name: traefik_net

configs:
  "nginx.conf":
    file: ./config/mete/nginx.conf
