version: '3.7'

services:
  proxy:
    image: traefik:v2.7
    environment:
      CF_API_EMAIL: account+cloudflare@chaosdorf.de
      CF_API_KEY_FILE: /run/secrets/CF_API_KEY
    configs:
      - source: static2
        target: /etc/traefik/traefik.toml
      - source: dynamic
        target: /etc/traefik/dynamic.toml
    secrets:
      - CF_API_KEY
      - TRAEFIK_DIGEST_AUTH
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme2:/etc/traefik/acme
      - tmp:/tmp
    networks:
      - traefik
    ports:
      - published: 80
        target: 80
        mode: host
      - published: 443
        target: 443
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 60s
        max_attempts: 5
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.125'
          memory: 16M
      labels:
        - traefik.docker.network=traefik_net
        - "traefik.http.routers.traefik-https.rule=Host(`traefik.chaosdorf.space`) || Host(`traefik`)"
        - traefik.http.routers.traefik-https.tls=true
        - traefik.http.routers.traefik-https.tls.certresolver=default
        - traefik.http.routers.traefik-https.tls.domains[0].main=*.chaosdorf.space
        - traefik.http.routers.traefik-https.middlewares=global-headers@file,traefik-error@docker,traefik-auth@docker
        - traefik.http.routers.traefik-https.service=api@internal
        # https://github.com/containous/traefik/issues/5732
        - traefik.http.services.traefik.loadbalancer.server.port=1234
        - traefik.http.middlewares.traefik-error.errors.status=403,404,429,500,503
        - traefik.http.middlewares.traefik-error.errors.service=error@docker
        - traefik.http.middlewares.traefik-error.errors.query=/{status}.html
        - traefik.http.middlewares.traefik-auth.digestauth.usersfile=/run/secrets/TRAEFIK_DIGEST_AUTH
        - traefik.http.middlewares.traefik-auth.digestauth.removeheader=true
  error:
    image: guillaumebriday/traefik-custom-error-pages:latest
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 60s
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
        reservations:
          cpus: '0.0625'
          memory: 4M
      labels:
        - traefik.docker.network=traefik_net
        - traefik.http.services.error.loadbalancer.server.port=80
        - "traefik.http.routers.error.rule=HostRegexp(`{host:.+}`)"
        - traefik.http.routers.error.priority=1 # low priority as fallback

volumes:
  acme2:
  tmp:

networks:
  traefik:
    driver: overlay
    external: true
    name: traefik_net

configs:
  static2:
    file: ../configs/traefik-static.toml
  dynamic:
    file: ../configs/traefik-dynamic.toml

secrets:
  CF_API_KEY:
    external: true
  TRAEFIK_DIGEST_AUTH:
    external: true
